### ISSUE TITLE
No access to admin for windows users not being 'Administrators'

### ISSUE THREAD

**Issue by Kulvis** [BVNetwork/Relations#3]
I'm not able to access Relations admin interface because of windows authentication and my user is not a member of the 'Administrators' group, but still needs access to the Relations sections. System.Web.Secutiry.Roles.IsUserInRole is used to do this check in RelationsAdmin.aspx.cs PageLoad, and I guess this doesn't take the virtual roles into consideration. 

Could this be change to use EPiServer.Security.PrincipalInfo.CurrentPrincipal.IsInRole or location tag in web.config?

**Comment by laerum** [comment]
Good point. I will fix this in the next release!

**Comment by Kulvis** [comment]
Perfect. When is the next release?

**Comment by laerum** [comment]
Just now! Version 4.1.7 is soon available in the nuget feed. Source code is updated. Sorry for the delay.
