### ISSUE TITLE
Error when getting relations that contains deleted Content

### ISSUE THREAD

**Issue by Aldarom** [BVNetwork/Relations#5]
Hi.

After we have upgraded to EPiserver 10 and the Relations Module to the latest version, we have found an error when getting pages with the method "GetPagesRelated". When the relation contains references to content that has been deleted, the method throws an exception.

>  ERROR Regjeringen.Relations.RelationsService: Error getting related pages from Relation: Content with id ** was not found

With this SQL-query we were able to find over 18.000 references that have been deleted, but still in the relations-database:
`SELECT *
  FROM [dbo].[EPiCodeRelations_Relation] 
  WHERE PageIdLeft NOT IN (SELECT pkID FROM tblContent) OR PageIdRight NOT IN (SELECT pkID from tblContent)`

**Comment by tomahg** [comment]
Looks like changing a few lines in PageEngine.GetPage(int page) from...
```
PageData pageData = ServiceLocator.Current.GetInstance<IContentRepository>().Get<IContent>(pageRef) as PageData;
return pageData;
```
...to...
```
IContent pageData;
ServiceLocator.Current.GetInstance<IContentRepository>().TryGet(pageRef, out pageData);
return pageData as PageData;
```
...solves the problem.
